# Site settings
title: Portfolio | Alejandro García Salas
email: garciasalasalejandro@gmail.com
description: This is Alejandro García Salas' Portfolio
baseurl: "/portfolio" # the subpath of your site, e.g. /blog/
url: "http://alejandrogarciasalas.me" # the base hostname & protocol for your site
# baseurl: ""
# url: ""
twitter_username: findAlejandro
github_username:  alejandrogarciasalas

# Google analytics
google_analytics: True

# Build settings
markdown: kramdown
sass:
  compressed: true